[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --no-header
# Bo qua cac thu muc khong phai test
norecursedirs = .venv venv .git __pycache__ hadoop .checkpoints checkpoints
